# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DjServerGui.ui'
#
# Created: Sun Jan 16 05:35:29 2011
#      by: PyQt4 UI code generator 4.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ServerWindow(object):
    def setupUi(self, ServerWindow):
        ServerWindow.setObjectName(_fromUtf8("ServerWindow"))
        ServerWindow.resize(800, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ServerWindow.sizePolicy().hasHeightForWidth())
        ServerWindow.setSizePolicy(sizePolicy)
        ServerWindow.setMinimumSize(QtCore.QSize(800, 600))
        ServerWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtGui.QWidget(ServerWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.tabWidget = QtGui.QTabWidget(self.groupBox_2)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 687, 508))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.formLayout = QtGui.QFormLayout(self.tab)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        spacerItem = QtGui.QSpacerItem(654, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout.setItem(0, QtGui.QFormLayout.SpanningRole, spacerItem)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonAddNew = QtGui.QPushButton(self.tab)
        self.pushButtonAddNew.setObjectName(_fromUtf8("pushButtonAddNew"))
        self.horizontalLayout.addWidget(self.pushButtonAddNew)
        self.pushButtonDelete = QtGui.QPushButton(self.tab)
        self.pushButtonDelete.setObjectName(_fromUtf8("pushButtonDelete"))
        self.horizontalLayout.addWidget(self.pushButtonDelete)
        self.pushButtonClear = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonClear.sizePolicy().hasHeightForWidth())
        self.pushButtonClear.setSizePolicy(sizePolicy)
        self.pushButtonClear.setObjectName(_fromUtf8("pushButtonClear"))
        self.horizontalLayout.addWidget(self.pushButtonClear)
        spacerItem1 = QtGui.QSpacerItem(288, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.pushButtonMoveUp = QtGui.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.pushButtonMoveUp.setFont(font)
        self.pushButtonMoveUp.setObjectName(_fromUtf8("pushButtonMoveUp"))
        self.gridLayout.addWidget(self.pushButtonMoveUp, 1, 1, 1, 1)
        self.pushButtonMoveDown = QtGui.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.pushButtonMoveDown.setFont(font)
        self.pushButtonMoveDown.setObjectName(_fromUtf8("pushButtonMoveDown"))
        self.gridLayout.addWidget(self.pushButtonMoveDown, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 328, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 3, 1, 1, 1)
        self.tableViewSong = QtGui.QTableView(self.tab)
        self.tableViewSong.setObjectName(_fromUtf8("tableViewSong"))
        self.gridLayout.addWidget(self.tableViewSong, 1, 0, 3, 1)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.gridLayout)
        spacerItem3 = QtGui.QSpacerItem(20, 425, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtGui.QFormLayout.LabelRole, spacerItem3)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem4 = QtGui.QSpacerItem(608, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 428, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 1, 0, 2, 1)
        self.graphicsViewBarChart = QtGui.QGraphicsView(self.tab_2)
        self.graphicsViewBarChart.setObjectName(_fromUtf8("graphicsViewBarChart"))
        self.gridLayout_2.addWidget(self.graphicsViewBarChart, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem6 = QtGui.QSpacerItem(20, 328, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 1, 1, 1, 1)
        self.tableViewRequest = QtGui.QTableView(self.tab_3)
        self.tableViewRequest.setObjectName(_fromUtf8("tableViewRequest"))
        self.gridLayout_5.addWidget(self.tableViewRequest, 0, 0, 2, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 2, 2)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 0, 1, 1)
        ServerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ServerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile_s = QtGui.QMenu(self.menubar)
        self.menuFile_s.setObjectName(_fromUtf8("menuFile_s"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        ServerWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ServerWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ServerWindow.setStatusBar(self.statusbar)
        self.actionAddPlaylist = QtGui.QAction(ServerWindow)
        self.actionAddPlaylist.setObjectName(_fromUtf8("actionAddPlaylist"))
        self.actionClose = QtGui.QAction(ServerWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionAbout = QtGui.QAction(ServerWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile_s.addAction(self.actionAddPlaylist)
        self.menuFile_s.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile_s.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(ServerWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButtonAddNew, QtCore.SIGNAL(_fromUtf8("clicked()")), ServerWindow.addNewSong)
        QtCore.QObject.connect(self.pushButtonDelete, QtCore.SIGNAL(_fromUtf8("clicked()")), ServerWindow.deleteSong)
        QtCore.QObject.connect(self.pushButtonClear, QtCore.SIGNAL(_fromUtf8("clicked()")), ServerWindow.clearSongList)
        QtCore.QObject.connect(self.pushButtonMoveUp, QtCore.SIGNAL(_fromUtf8("clicked()")), ServerWindow.moveSongUp)
        QtCore.QObject.connect(self.pushButtonMoveDown, QtCore.SIGNAL(_fromUtf8("clicked()")), ServerWindow.moveSongDown)
        QtCore.QObject.connect(self.actionAddPlaylist, QtCore.SIGNAL(_fromUtf8("triggered()")), ServerWindow.importPlayList)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL(_fromUtf8("triggered()")), ServerWindow.closeApp)
        QtCore.QMetaObject.connectSlotsByName(ServerWindow)

    def retranslateUi(self, ServerWindow):
        ServerWindow.setWindowTitle(QtGui.QApplication.translate("ServerWindow", "FeedDJ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ServerWindow", "Feed DJ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAddNew.setText(QtGui.QApplication.translate("ServerWindow", "Add New", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDelete.setText(QtGui.QApplication.translate("ServerWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonClear.setText(QtGui.QApplication.translate("ServerWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMoveUp.setText(QtGui.QApplication.translate("ServerWindow", "↑", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMoveDown.setText(QtGui.QApplication.translate("ServerWindow", "↓", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("ServerWindow", "Voting", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("ServerWindow", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("ServerWindow", "Requests", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile_s.setTitle(QtGui.QApplication.translate("ServerWindow", "File(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("ServerWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddPlaylist.setText(QtGui.QApplication.translate("ServerWindow", "Add Playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("ServerWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("ServerWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

